"""Object store protocol used by learning and answering artifacts."""

from __future__ import annotations

from typing import Protocol


class ObjectStore(Protocol):
    """Minimal object store interface for DiracData artifacts."""

    def write_bytes(self, key: str, value: bytes, content_type: str | None = None) -> None: ...
    def read_bytes(self, key: str) -> bytes: ...
    def write_text(self, key: str, value: str, content_type: str = "text/plain") -> None: ...
    def read_text(self, key: str) -> str: ...
    def write_json(self, key: str, value: object) -> None: ...
    def read_json(self, key: str) -> object: ...
    def exists(self, key: str) -> bool: ...
    def list_keys(self, prefix: str = "") -> list[str]: ...

