"""diracdata.stores -- the object-store abstraction the whole harness persists through (artifacts,
the lake pointer, checkpoints, memory). One `Store` protocol; pluggable backends.

Backends: local (filesystem), s3 (S3/MinIO, works), caching (read-through wrapper). Azure Blob and
GCS are STUBS behind optional extras -- they satisfy the same protocol so nothing downstream changes
when they land. `store_from_settings` picks the backend from config (DIRACDATA_OBJECT_STORE).
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class Store(Protocol):
    """Key/value blob store with object-store-style keys. All backends implement this exactly."""

    def write_bytes(self, key: str, value: bytes, content_type: str | None = None) -> None: ...
    def read_bytes(self, key: str) -> bytes: ...
    def write_text(self, key: str, value: str, content_type: str = "text/plain") -> None: ...
    def read_text(self, key: str) -> str: ...
    def write_json(self, key: str, value: object) -> None: ...
    def read_json(self, key: str) -> object: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...
    def list_keys(self, prefix: str = "") -> list[str]: ...
